### ISSUE TITLE
Cull Leaves incompatible with Sodium

### ISSUE THREAD

**Issue by Albaraa-PC** [TeamMidnightDust/BetterLeavesPack#34]
Error Code:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.5.2 with version 0.5.2 that is compatible with:
		 - cullleaves 3.1.0
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.5.2 is incompatible with version 3.1.0 or earlier of mod 'Cull Leaves' (cullleaves), but a matching version is present: 3.1.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Motschen** [comment]
Wrong repo ;)
Also, this is fixed now.
